/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dismoto.views.formularios;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Orlando
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public static FrmPrincipal frmPrincipal;
    private  FrmPrincipal() {
        initComponents();
    }
    
    public synchronized static FrmPrincipal instanciaFormulario(){
        if(frmPrincipal==null){
            frmPrincipal= new FrmPrincipal();
        }
        return frmPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnZonaTrabajo = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoUsuarios = new javax.swing.JMenuItem();
        mnuArchivoClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuArchivoCambioClave = new javax.swing.JMenuItem();
        mnuArchivoCambioUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuMovimiento = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dismoto/utils/imagenes/Archivo.png"))); // NOI18N
        mnuArchivo.setMnemonic('f');
        mnuArchivo.setText("Archivo");

        mnuArchivoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dismoto/utils/imagenes/User2.png"))); // NOI18N
        mnuArchivoUsuarios.setMnemonic('o');
        mnuArchivoUsuarios.setText("Usuarios");
        mnuArchivoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoUsuariosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoUsuarios);

        mnuArchivoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dismoto/utils/imagenes/Clientes.png"))); // NOI18N
        mnuArchivoClientes.setMnemonic('s');
        mnuArchivoClientes.setText("Clientes");
        mnuArchivo.add(mnuArchivoClientes);
        mnuArchivo.add(jSeparator1);

        jMenuItem1.setText("Empleado");
        mnuArchivo.add(jMenuItem1);

        mnuArchivoCambioClave.setText("Cambio Clave");
        mnuArchivoCambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoCambioClaveActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoCambioClave);

        mnuArchivoCambioUsuario.setText("Cambio Usuario");
        mnuArchivo.add(mnuArchivoCambioUsuario);
        mnuArchivo.add(jSeparator2);

        mnuArchivoSalir.setText("Salir");
        mnuArchivo.add(mnuArchivoSalir);

        menuBar.add(mnuArchivo);

        mnuMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dismoto/utils/imagenes/movimiento.png"))); // NOI18N
        mnuMovimiento.setMnemonic('e');
        mnuMovimiento.setText("Movimientos");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Nueva Orden");
        mnuMovimiento.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Reportes");
        mnuMovimiento.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        mnuMovimiento.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        mnuMovimiento.add(deleteMenuItem);

        menuBar.add(mnuMovimiento);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dismoto/utils/imagenes/Ayuda.png"))); // NOI18N
        mnuAyuda.setMnemonic('h');
        mnuAyuda.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca de..");
        mnuAyuda.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Ayuda");
        mnuAyuda.add(aboutMenuItem);

        menuBar.add(mnuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnZonaTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnZonaTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArchivoCambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoCambioClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoCambioClaveActionPerformed

    private void mnuArchivoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoUsuariosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuArchivoUsuariosActionPerformed

   

    public JDesktopPane getDpnZonaTrabajo() {
        return dpnZonaTrabajo;
    }

    public JMenu getMnuArchivo() {
        return mnuArchivo;
    }

    public JMenuItem getMnuArchivoCambioClave() {
        return mnuArchivoCambioClave;
    }

    public JMenuItem getMnuArchivoCambioUsuario() {
        return mnuArchivoCambioUsuario;
    }

    public JMenuItem getMnuArchivoClientes() {
        return mnuArchivoClientes;
    }

 
    

    public JMenuItem getMnuArchivoSalir() {
        return mnuArchivoSalir;
    }

    public JMenuItem getMnuArchivoUsuarios() {
        return mnuArchivoUsuarios;
    }
    /*
    @return Devuelve el mnuAyuda
    */

    public JMenu getMnuAyuda() {
        return mnuAyuda;
    }
 
    public JMenu getMnuMovimiento() {
        return mnuMovimiento;
    }

    public JMenuItem getPasteMenuItem() {
        return pasteMenuItem;
    }

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane dpnZonaTrabajo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoCambioClave;
    private javax.swing.JMenuItem mnuArchivoCambioUsuario;
    private javax.swing.JMenuItem mnuArchivoClientes;
    private javax.swing.JMenuItem mnuArchivoSalir;
    private javax.swing.JMenuItem mnuArchivoUsuarios;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuMovimiento;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
