/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.views.usuarios;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Orlando
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {
    private boolean estado = false;
     private final  String ruta = "/sistema/utils/imagenes/";

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuarios() {
        initComponents();       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        PnlContraseña = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PnlContraseña2 = new javax.swing.JPanel();
        TxtUsuario2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PnlContraseña3 = new javax.swing.JPanel();
        TxtUsuario3 = new javax.swing.JTextField();
        PnlContraseña4 = new javax.swing.JPanel();
        TxtUsuario4 = new javax.swing.JTextField();
        PnlContraseña5 = new javax.swing.JPanel();
        rbAdministrador = new javax.swing.JRadioButton();
        rbUsuario = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        PnlContraseña6 = new javax.swing.JPanel();
        TxtUsuario6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleBackground"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso al usuario");

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Clave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta +"cancel.png")));
        BtnSalir.setText("Cancelar");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta +"okAceptar.png")));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 117, -1));

        PnlContraseña.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        PnlContraseña.setForeground(new java.awt.Color(255, 0, 0));

        TxtUsuario.setBackground(new java.awt.Color(255, 102, 102));
        TxtUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtUsuario.setToolTipText("");
        TxtUsuario.setBorder(null);
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContraseñaLayout = new javax.swing.GroupLayout(PnlContraseña);
        PnlContraseña.setLayout(PnlContraseñaLayout);
        PnlContraseñaLayout.setHorizontalGroup(
            PnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContraseñaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        PnlContraseñaLayout.setVerticalGroup(
            PnlContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(PnlContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Conf Clave:");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 30));
        jLabel4.getAccessibleContext().setAccessibleName("<html>Confirmacion         Clave:</html>");

        PnlContraseña2.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        PnlContraseña2.setForeground(new java.awt.Color(255, 0, 0));

        TxtUsuario2.setBackground(new java.awt.Color(255, 102, 102));
        TxtUsuario2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtUsuario2.setToolTipText("");
        TxtUsuario2.setBorder(null);
        TxtUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContraseña2Layout = new javax.swing.GroupLayout(PnlContraseña2);
        PnlContraseña2.setLayout(PnlContraseña2Layout);
        PnlContraseña2Layout.setHorizontalGroup(
            PnlContraseña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContraseña2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TxtUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        PnlContraseña2Layout.setVerticalGroup(
            PnlContraseña2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(PnlContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 30));

        PnlContraseña3.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        PnlContraseña3.setForeground(new java.awt.Color(255, 0, 0));

        TxtUsuario3.setBackground(new java.awt.Color(255, 102, 102));
        TxtUsuario3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtUsuario3.setToolTipText("");
        TxtUsuario3.setBorder(null);
        TxtUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContraseña3Layout = new javax.swing.GroupLayout(PnlContraseña3);
        PnlContraseña3.setLayout(PnlContraseña3Layout);
        PnlContraseña3Layout.setHorizontalGroup(
            PnlContraseña3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContraseña3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TxtUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        PnlContraseña3Layout.setVerticalGroup(
            PnlContraseña3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(PnlContraseña3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        PnlContraseña4.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        PnlContraseña4.setForeground(new java.awt.Color(255, 0, 0));

        TxtUsuario4.setBackground(new java.awt.Color(255, 102, 102));
        TxtUsuario4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtUsuario4.setToolTipText("");
        TxtUsuario4.setBorder(null);
        TxtUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContraseña4Layout = new javax.swing.GroupLayout(PnlContraseña4);
        PnlContraseña4.setLayout(PnlContraseña4Layout);
        PnlContraseña4Layout.setHorizontalGroup(
            PnlContraseña4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContraseña4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TxtUsuario4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        PnlContraseña4Layout.setVerticalGroup(
            PnlContraseña4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtUsuario4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(PnlContraseña4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        PnlContraseña5.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(102, 102, 0))); // NOI18N
        PnlContraseña5.setForeground(new java.awt.Color(51, 51, 255));

        rbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        btgGrupo.add(rbAdministrador);
        rbAdministrador.setText("Administrador");

        rbUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btgGrupo.add(rbUsuario);
        rbUsuario.setText("Usuario");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta +"userk.png")));
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout PnlContraseña5Layout = new javax.swing.GroupLayout(PnlContraseña5);
        PnlContraseña5.setLayout(PnlContraseña5Layout);
        PnlContraseña5Layout.setHorizontalGroup(
            PnlContraseña5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContraseña5Layout.createSequentialGroup()
                .addGroup(PnlContraseña5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContraseña5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PnlContraseña5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbUsuario)
                            .addComponent(rbAdministrador)))
                    .addGroup(PnlContraseña5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PnlContraseña5Layout.setVerticalGroup(
            PnlContraseña5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContraseña5Layout.createSequentialGroup()
                .addComponent(rbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbUsuario)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(PnlContraseña5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 260));

        PnlContraseña6.setBackground(new java.awt.Color(255, 255, 255));
        PnlContraseña6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        PnlContraseña6.setForeground(new java.awt.Color(255, 0, 0));

        TxtUsuario6.setBackground(new java.awt.Color(255, 102, 102));
        TxtUsuario6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtUsuario6.setToolTipText("");
        TxtUsuario6.setBorder(null);
        TxtUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContraseña6Layout = new javax.swing.GroupLayout(PnlContraseña6);
        PnlContraseña6.setLayout(PnlContraseña6Layout);
        PnlContraseña6Layout.setHorizontalGroup(
            PnlContraseña6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContraseña6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TxtUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        PnlContraseña6Layout.setVerticalGroup(
            PnlContraseña6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(PnlContraseña6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Correo:");
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
      
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void TxtUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario2ActionPerformed

    private void TxtUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario3ActionPerformed

    private void TxtUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario4ActionPerformed

    private void TxtUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario6ActionPerformed

    
    
    public JButton getBtnAceptar() {
        return BtnAceptar;
    }

    

    public JTextField getTxtUsuario() {
        return TxtUsuario;
    }

    

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public JButton getBtnSalir() {
        return BtnSalir;
    }
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JPanel PnlContraseña;
    private javax.swing.JPanel PnlContraseña2;
    private javax.swing.JPanel PnlContraseña3;
    private javax.swing.JPanel PnlContraseña4;
    private javax.swing.JPanel PnlContraseña5;
    private javax.swing.JPanel PnlContraseña6;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JTextField TxtUsuario2;
    private javax.swing.JTextField TxtUsuario3;
    private javax.swing.JTextField TxtUsuario4;
    private javax.swing.JTextField TxtUsuario6;
    private javax.swing.ButtonGroup btgGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbUsuario;
    // End of variables declaration//GEN-END:variables
}
